### ISSUE TITLE
Server won't start 

### ISSUE THREAD

**Issue by Sartharon** [JordanPlayz158/killing-floor-2-pterodactyl#1]
As I'm pretty new to Pterodactyl I can't seem to be able to get the server running:

What I did:
-Created a docker image from this repo
-Created a new Egg in the Source Engine Nest
-There I copied the Process Management settings from Pterodactyls' Custom Source Engine Egg
-Used the newly created docker image
-As Start command i tried 'start' and the script from your 'main.firststart' (Still not sure what I should enter there)
-Restarted the pterodactyl-daemon
-Created a new server from the new egg
-Started the server

What Error I get:

`[Pterodactyl Daemon] A fatal error was encountered while starting this server.`

Pterodactyl Diagnostics:

````
==[ Pterodactyl Daemon: Diagnostics Report ]==
--| Software Versions
    - Daemon:  0.6.12
    - Node.js: v8.10.0
    - Docker:  Docker version 18.09.7, build 2d0083d


--| Daemon Configuration
    - SSL Enabled: false
    - Port:        8080
    - Upload Size: 100
    - Remote Host: http://192.168.0.69

--| Docker Information
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 18
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-62-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.852GiB
Name: minecraft
ID: 2XC7:S52N:62GS:TUIA:4OOY:554F:CIFR:IRHM:GMIC:3DOM:AG4U:YT3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false



--| Docker Containers
CONTAINER ID        NAMES                                  IMAGE                           STATUS
ff5daa08b5f6        206b2950-eaa8-418e-9e93-d76f1f8b5f21   killingfloor2                   Created
1ed43004c011        epic_curran                            killingfloor2                   Exited (127) 37 minutes ago
1e9a90c5d94e        0af6395e-036f-4411-a8e0-b0606eb80373   quay.io/pterodactyl/core:java   Exited (0) About an hour ago


--| Latest Logs
03:00:03.581Z  INFO wings: Server status has been changed to OFF (server=0af6395e-036f-4411-a8e0-b0606eb80373)
03:00:05.044Z  WARN wings: Server detected as crashed! Attempting server reboot. (server=0af6395e-036f-4411-a8e0-b0606eb80373, ExitCode=0, OOMKilled=false, Error="")
03:00:05.044Z  INFO wings: Server status has been changed to STARTING (server=0af6395e-036f-4411-a8e0-b0606eb80373)
03:00:31.945Z  INFO wings: Server status has been changed to ON (server=0af6395e-036f-4411-a8e0-b0606eb80373)
13:19:24.254Z  WARN wings: Container was not found. Attempting to recreate it. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:24.257Z  INFO wings: Checking if we need to update image killingfloor2, if so it will happen now.
13:19:25.739Z ERROR wings: Encountered an error while attempting to fetch a fresh image. Continuing with existing system image. (image=killingfloor2)
    Error: (HTTP code 404) unexpected - pull access denied for killingfloor2, repository does not exist or may require 'docker login' 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:9)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
13:19:26.468Z  WARN wings: Server booting is now BLOCKED. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.469Z  INFO wings: Blocking server boot until option installation process is completed. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.527Z  INFO wings: No installation script was defined for this egg, skipping rest of process. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.527Z  INFO wings: Server booting is now UNBLOCKED. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.536Z  INFO wings: Server has been unsuspended. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.691Z  INFO wings: Notified remote panel of server install status.
13:19:26.692Z  INFO wings: Server status has been changed to STARTING (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.692Z  INFO wings: Server status has been changed to STOPPING (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.692Z  INFO wings: Server status has been changed to OFF (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:26.798Z  INFO wings: Checking if we need to update image killingfloor2, if so it will happen now.
13:19:28.298Z ERROR wings: Encountered an error while attempting to fetch a fresh image. Continuing with existing system image. (image=killingfloor2)
    Error: (HTTP code 404) unexpected - pull access denied for killingfloor2, repository does not exist or may require 'docker login' 
        at /srv/daemon/node_modules/docker-modem/lib/modem.js:257:17
        at IncomingMessage.<anonymous> (/srv/daemon/node_modules/docker-modem/lib/modem.js:284:9)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1064:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
13:19:28.731Z  INFO wings: Completed rebuild process for server container. (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:28.731Z  INFO wings: Server status has been changed to STARTING (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:28.747Z  INFO wings: Server status has been changed to OFF (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:28.749Z ERROR wings: No egg configuration was defined for this egg. (server=5c1b6371-d6a1-4758-9394-98e989585af5, err.code=NO_EGG_CONFIGURATION)
    Error: No egg configuration was defined for this egg.
        at Promise (/srv/daemon/src/services/index.js:80:31)
        at new Promise (<anonymous>)
        at Core.onPreflight (/srv/daemon/src/services/index.js:78:16)
        at Server.preflight (/srv/daemon/src/controllers/server.js:275:22)
        at Async.series.callback (/srv/daemon/src/controllers/server.js:366:22)
        at /srv/daemon/node_modules/async/dist/async.js:3880:24
        at replenish (/srv/daemon/node_modules/async/dist/async.js:1011:17)
        at iterateeCallback (/srv/daemon/node_modules/async/dist/async.js:995:17)
        at /srv/daemon/node_modules/async/dist/async.js:969:16
        at /srv/daemon/node_modules/async/dist/async.js:3885:13
13:19:28.749Z ERROR wings: No egg configuration was defined for this egg. (server=5c1b6371-d6a1-4758-9394-98e989585af5, err.code=NO_EGG_CONFIGURATION)
    Error: No egg configuration was defined for this egg.
        at Promise (/srv/daemon/src/services/index.js:80:31)
        at new Promise (<anonymous>)
        at Core.onPreflight (/srv/daemon/src/services/index.js:78:16)
        at Server.preflight (/srv/daemon/src/controllers/server.js:275:22)
        at Async.series.callback (/srv/daemon/src/controllers/server.js:366:22)
        at /srv/daemon/node_modules/async/dist/async.js:3880:24
        at replenish (/srv/daemon/node_modules/async/dist/async.js:1011:17)
        at iterateeCallback (/srv/daemon/node_modules/async/dist/async.js:995:17)
        at /srv/daemon/node_modules/async/dist/async.js:969:16
        at /srv/daemon/node_modules/async/dist/async.js:3885:13
13:19:35.106Z  INFO wings: Server status has been changed to STARTING (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:35.122Z  INFO wings: Server status has been changed to OFF (server=5c1b6371-d6a1-4758-9394-98e989585af5)
13:19:35.122Z ERROR wings: No egg configuration was defined for this egg. (server=5c1b6371-d6a1-4758-9394-98e989585af5, err.code=NO_EGG_CONFIGURATION)
    Error: No egg configuration was defined for this egg.
        at Promise (/srv/daemon/src/services/index.js:80:31)
        at new Promise (<anonymous>)
        at Core.onPreflight (/srv/daemon/src/services/index.js:78:16)
        at Server.preflight (/srv/daemon/src/controllers/server.js:275:22)
        at Async.series.callback (/srv/daemon/src/controllers/server.js:366:22)
        at /srv/daemon/node_modules/async/dist/async.js:3880:24
        at replenish (/srv/daemon/node_modules/async/dist/async.js:1011:17)
        at iterateeCallback (/srv/daemon/node_modules/async/dist/async.js:995:17)
        at /srv/daemon/node_modules/async/dist/async.js:969:16
        at /srv/daemon/node_modules/async/dist/async.js:3885:13
```

**Comment by JordanPlayz158** [comment]
Yeah it's not perfect but I think I can help you

**Comment by JordanPlayz158** [comment]
Sorry for late response I didn't get email notification so I'm sorry for that

**Comment by JordanPlayz158** [comment]
Do you have discord

**Comment by Sartharon** [comment]
Yeah I do
but solved my problem in that I build my own egg based on the official 'quay.io/pterodactyl/core:source'  docker image.
Add me on discord if you want we can look over my egg and share it here if you'd like

Sartharon
#2222

**Comment by JordanPlayz158** [comment]
K I'll add you
